### ISSUE TITLE
发现了拼写错误

### ISSUE THREAD

**Issue by cjdd101** [waylau/apache-shiro-1.2.x-reference#14]
In Core - 6.1 Permission
为什么？因为第二个例子表明“对于下面的代码块的执行，你必须能够打印到任何打印机”。**但请记住 "pinter:print" 是等价 "priner:print:*" 的！**
加粗部分两个printer都有拼写错误。

anyway，感谢作者大大的辛苦付出！

**Comment by waylau** [comment]
@cjdd101 

感谢反馈，已经修正！
