### ISSUE TITLE
链接失效

### ISSUE THREAD

**Issue by Ahaochan** [waylau/apache-shiro-1.2.x-reference#7]
https://github.com/waylau/apache-shiro-1.2.x-reference/blob/master/SUMMARY.md

显示为如下样式
```
[1. Introduction 介绍](I. Overview 总览/1. Introduction 介绍.md)
```

**Comment by mxHoward** [comment]
https://waylau.gitbooks.io/apache-shiro-1-2-x-reference/

该gitbook上有些链接失效，显示page not found

**Comment by waylau** [comment]
@mxHoward  连接是在的。

**Comment by waylau** [comment]
@Ahaochan  路径里面不能有空格。
